### ISSUE TITLE
Expose tag registration

### ISSUE THREAD

**Issue by matthewp** [canjs/can-view-callbacks#23]
For https://github.com/canjs/can-component/issues/10 we need a way to know when tags are created by callbacks.tag() and a list of all tags that have been registered previously.

This could be provided in 2 ways currently:

**Previously registered tags**

```js
var registeredTags = Object.keys(callbacks._tags);
```

**Notification of tag registration**

```js
var tag = callbacks.tag;
callbacks.tag = function(tagName){
 ...
};
```

The latter is *ok*, if not ideal, but the former at least needs to be exported as a non-underscored property.

We could set up some eventing thing for the latter case but that feels like overkill to me. Wrapping might be the best method.

**Comment by justinbmeyer** [comment]
Problem with the wrapping is that when it's wrapped it is only deterministic if modules all load the wrapper.

**Comment by matthewp** [comment]
I don't understand what you mean. What problem are you seeing? Why do we need determinism? As long as modules do not keep a local reference of `callbacks.tag`, it doesn't matter what order things are loaded.  Although people *might* keep a local reference of callbacks.tag so that's a reasonable argument against wrapping.

**Comment by matthewp** [comment]
I think if callbacks.tag internally called a callbacks._tag it would resolve my issues. This way you could do:

**wrapper.js**

```js
var callbacks = require("can-view-callbacks");

var tag = callbacks._tag;
callbacks._tag = function(){
  // custom logic here
};
```

**app.js**

```js
var tag = require("can-view-callbacks");

tag("some-tag", function() { ... });
```

And since callbacks.tag is internally calling callbacks._tag, our wrapper gets to intercept that call.

**Comment by matthewp** [comment]
Closing this in favor of https://github.com/canjs/can-custom-elements

**Comment by justinbmeyer** [comment]
I think we should keep this open.  Is it possible to make custom elements from existing components?  If yes, this is a good option.

**Comment by justinbmeyer** [comment]
I guess we are pretty much doing this now.  Closing.
