### ISSUE TITLE
Plain JS object scope dosent work with subtemplate

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-view-callbacks#41]
In the custom tag callback, plain object scope throws error like in this jsbin http://jsbin.com/wesinuc/edit?html,js,console,output

**Comment by justinbmeyer** [comment]
works if the context has an observable: http://jsbin.com/febakiq/edit?html,js,console,output

**Comment by cherifGsoul** [comment]
@justinbmeyer I got ```scope.__cache is undefined``` http://jsbin.com/yoyise/edit?html,js,console

**Comment by justinbmeyer** [comment]
The issue here is that `subtemplate` isn't wrapped with something that converts the data passed to it to a scope object.  This is a problem with can-stache.  

```
var frag = tagData.subtemplate({
  first: 'Justin'
  }, tagData.options)
```

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #208](https://github.com/canjs/can-stache/issues/208) via [**ZenHub**](https://www.zenhub.com/)
