### ISSUE TITLE
Registered attr doesn’t work when defined after component is defined

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-view-callbacks#43]
I have an app where I’d like to define a component and then later define an `attr` callback, like so:

```javascript
can.Component.extend({
  tag: 'home-page',
  view: can.stache('<p update-content>Not updated</p>')
});

can.view.callbacks.attr('update-content', function(element) {
  element.textContent = 'Updated';
});
```

It feels like this should work because the `attr` is defined by the time the component is used in the app, but right now the `attr` has to be defined before the component. It’s not documented either way, so I’m not 100% sure if this is a bug or enhancement request. 😊

JS Bin: https://jsbin.com/fisavalige/1/edit?html,js,output

**Comment by phillipskevin** [comment]
A warning was added with https://github.com/canjs/can-view-callbacks/pull/58 so people are aware that `attr`s like this aren't going to work. I'm going to close this for now, but feel free to re-open if you think we should try to address this further.
