### ISSUE TITLE
Fix the attr demos

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-view-callbacks#53]
It doesn’t look like any of the demos are working correctly on this page: https://canjs.com/doc/can-view-callbacks.attr.html

**Comment by phillipskevin** [comment]
Here is the error:
![image](https://user-images.githubusercontent.com/5851984/29322825-891d24bc-81a4-11e7-9ec4-22def1235ba9.png)

**Comment by chasenlehara** [comment]
Well I feel silly; I opened https://github.com/canjs/canjs/issues/3490 yesterday because I ran into this again. I think that’s probably the better issue to keep open because the demos are in that repo.

Closing this one in favor of https://github.com/canjs/canjs/issues/3490
